# Generated by Django 4.1.7 on 2023-04-04 21:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activityuser",
            name="priv_key",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="activityuser",
            name="pub_key",
            field=models.TextField(),
        ),
    ]
