# Generated by Django 4.1.7 on 2023-04-04 21:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_activityuser_priv_key_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("type", models.CharField(max_length=255)),
                ("actor", models.CharField(max_length=255)),
                ("to", models.TextField(null=True)),
                ("cc", models.TextField(null=True)),
                ("object", models.TextField(null=True)),
                ("content", models.TextField(null=True)),
                ("source", models.TextField(null=True)),
                ("published", models.DateTimeField(null=True)),
                ("deleted", models.DateTimeField(null=True)),
            ],
        ),
    ]
