# Generated by Django 4.1.7 on 2023-04-04 23:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_activity"),
    ]

    operations = [
        migrations.AddField(
            model_name="activityuser",
            name="followers",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="activityuser",
            name="following",
            field=models.IntegerField(default=0),
        ),
    ]
