# Generated by Django 4.1.7 on 2023-04-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_activityuser_followers_activityuser_following"),
    ]

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("actor", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("published", models.DateTimeField()),
                ("tags", models.TextField()),
            ],
        ),
    ]
