# Generated by Django 4.1.7 on 2023-04-08 22:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_note"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscoveredInstances",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=255, unique=True)),
                ("inbox", models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
