# Generated by Django 4.1.7 on 2023-04-08 22:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_discoveredinstances"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="tags",
            field=models.TextField(blank=True, null=True),
        ),
    ]
