# Generated by Django 4.1.7 on 2023-04-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_alter_note_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("preferred_username", models.CharField(max_length=255)),
                ("inbox", models.CharField(max_length=255)),
                ("outbox", models.CharField(max_length=255)),
                ("followers", models.CharField(max_length=255)),
                ("following", models.CharField(max_length=255)),
                ("public_key", models.TextField()),
                ("shared_inbox", models.CharField(max_length=255)),
            ],
        ),
    ]
