# Generated by Django 4.1.7 on 2023-04-09 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.profile"
            ),
        ),
    ]
