# Generated by Django 4.1.7 on 2023-04-09 23:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_follow"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={"verbose_name_plural": "Activities"},
        ),
        migrations.AlterModelOptions(
            name="discoveredinstances",
            options={
                "verbose_name": "Discovered Instance",
                "verbose_name_plural": "Discovered Instances",
            },
        ),
    ]
